### ISSUE TITLE
How to run a demo test on some images?

### ISSUE THREAD

**Issue by ronnie-tian** [svip-lab/PPGNet#3]
Hello, is there a demo to run on an image for a set of images? I noticed test.sh but it seems to run the training process. Thank you.

**Comment by allankevinrichie** [comment]
Hi @shawn-tian , I just fixed the error in the test script. However, since I‘m still working on re-organizing the checkpoints and some other code, I haven't uploaded the pre-trained model yet. So for now, you need to train the network before running the test script. Thanks for your interest in our work.

**Comment by ronnie-tian** [comment]
Ok, thank you very much for the quick feedback.

**Comment by siyuada** [comment]
Hey, will you release the checkpoint model later?

**Comment by asadabbas09** [comment]
Hi, 
Do you plan to release trained checkpoint model anytime soon?
